Vagrant.configure("2") do |config|
  config.vm.disk :disk, size: "5GB", primary: true
  config.vm.box = "hashicorp/bionic64"
  config.vm.hostname = "client-user"
  config.vm.network "public_network"
  
  config.vm.provision "shell", inline: <<-SHELL
    echo "------------------ UPDATE and UTILS -----------------"
    apt-get update
    apt-get install build-essential libssl-dev git zip unzip -y 
    echo "Done!"
    echo "-------------------- INSTALL WRK --------------------"
    git clone https://github.com/wg/wrk.git wrk
    cd wrk
    make
    cp wrk /usr/local/bin
    echo "Done!"
    echo "-------------- BENCHMARK VAGRANT ---------------"
    wrk -t1 -c100 -d3m http://192.168.1.19:8082
    echo "--------------- BENCHMARK DOCKER ----------------"
    wrk -t1 -c100 -d3m http://192.168.1.19:8081
    echo "-------------------------------------------------------"
    SHELL
end
